In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
path=(r"C:\Users\HP\Downloads\Salary_Data.csv")
df=pd.read_csv(path)
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [5]:
df.shape

(30, 2)

In [6]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [7]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [8]:
df.dtypes

YearsExperience    float64
Salary               int64
dtype: object

In [9]:
X=df.drop('YearsExperience',axis=1)
y=df['Salary']

In [10]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1234,test_size=0.30 )

In [11]:
X_train.shape,X_test.shape

((21, 1), (9, 1))

In [12]:
y_train.shape,y_test.shape

((21,), (9,))

In [13]:
df.shape

(30, 2)

In [14]:
X_train

Salary
13   57081
22  101302
24  109431
0    39343
2    37731
27  112635
26  116969
18   81363
5    56642
16   66029
25  105582
11   55794
9    57189
17   83088
29  121872
20   91738
12   56957
21   98273
6    60150
19   93940
15   67938

In [15]:
y_train

13     57081
22    101302
24    109431
0      39343
2      37731
27    112635
26    116969
18     81363
5      56642
16     66029
25    105582
11     55794
9      57189
17     83088
29    121872
20     91738
12     56957
21     98273
6      60150
19     93940
15     67938
Name: Salary, dtype: int64

In [16]:
X_test

Salary
7    54445
10   63218
4    39891
1    46205
28  122391
8    64445
3    43525
23  113812
14   61111

In [17]:
y_test

7      54445
10     63218
4      39891
1      46205
28    122391
8      64445
3      43525
23    113812
14     61111
Name: Salary, dtype: int64

In [18]:
X_train.ndim

2

In [19]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [20]:
# Model predictions happens X_test
y_predictions=LR.predict(X_test)

In [21]:
y_predictions

array([ 54445.,  63218.,  39891.,  46205., 122391.,  64445.,  43525.,
       113812.,  61111.])

In [22]:
y_test.shape,y_predictions.shape

((9,), (9,))

In [23]:
X_test

Salary
7    54445
10   63218
4    39891
1    46205
28  122391
8    64445
3    43525
23  113812
14   61111

In [24]:
X_test.iloc[0]
X_test.iloc[0].values

array([54445], dtype=int64)

In [25]:
LR.predict([X_test.iloc[0].values,
           X_test.iloc[1].values])

array([54445., 63218.])

In [26]:
ip1=[5]
LR.predict([ip1])

array([5.])

In [27]:
X_test.shape,y_test.shape,y_predictions.shape

((9, 1), (9,), (9,))

In [28]:
test_data=X_test
test_data['y_actual']=y_test
test_data['y_predictions']=y_predictions
test_data

Salary  y_actual  y_predictions
7    54445     54445        54445.0
10   63218     63218        63218.0
4    39891     39891        39891.0
1    46205     46205        46205.0
28  122391    122391       122391.0
8    64445     64445        64445.0
3    43525     43525        43525.0
23  113812    113812       113812.0
14   61111     61111        61111.0

In [29]:
print(y_test.values[:5])
# float 5. means 5.
print(y_predictions[:5])

[ 54445  63218  39891  46205 122391]
[ 54445.  63218.  39891.  46205. 122391.]


In [30]:
from sklearn.metrics import r2_score,mean_squared_error

In [32]:
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
RMSE=np.sqrt(MSE)
print("R-Square:",R2)
print("MSE:",MSE)
print("RMSE:")

R-Square: 1.0
MSE: 6.470390569303684e-23
RMSE:


In [33]:
s=0
for i in range(len(y_test)):
    v1=y_test.values[i]-y_predictions[i]
    v2=v1**2
    s=s+v2
print(s/len(y_test))

6.470390569303684e-23


In [36]:
LR.coef_
print("the coefficient yearsof experience:",LR.coef_)

the coefficient yearsof experience: [1.]


In [37]:
LR.intercept_

-1.4551915228366852e-11

In [38]:
X_train.columns

Index(['Salary'], dtype='object')

In [43]:
y=-1.45+1-.*Salary

SyntaxError: invalid syntax (2474589634.py, line 1)

In [44]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
# Threshold variance value
# we want to drop the feaure based on threshold
vt.fit(df)

VarianceThreshold(threshold=0)

In [45]:
dir(vt)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_transform',
 '_validate_data',
 'feature_names_in_',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_params',
 'get_support',
 'inverse_transform',
 'n_features_in_',
 'set_params',
 'threshold',
 'transform',
 'variances_']

In [46]:
vt.variances_

array([7.78515556e+00, 8.46600000e+04])

In [48]:
vt.get_support()

array([ True,  True])

In [49]:
vt.get_params()

{'threshold': 0}

In [50]:
vt.threshold

0

In [51]:
cols=vt.get_feature_names_out()
# the above syntax gives the column names
# These fetaure only we want include
df[cols]

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [52]:
path=r"C:\Users\HP\Downloads\Salary_Data.csv"
df=pd.read_csv(path)
df.head()
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
### Make sure before fitting the dataframe , do not include output column
X=df.drop('YearsExperience',axis=1)
# X it self a data frame
vt.fit(X)
vt.variances_
vt.get_support()
cols=vt.get_feature_names_out()
X[cols]

Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [54]:
from statsmodels.api import OLS 
OLS(y_train,X_train).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                 Salary   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          3.694e+32
Date:                Sat, 28 Dec 2024   Prob (F-statistic):                   3.81e-314
Time:                        15:10:08   Log-Likelihood:                          488.13
No. Observations:                  21   AIC:                                     -974.3
Df Residuals:                      20   BIC:                                     -973.2
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Salary         1.0000    5.2e-17   1.92e+16      0.000       1.000       1.000
==============================================================================
Omnibus:                        3.403   Durbin-Watson:                   0.280
Prob(Omnibus):                  0.182   Jarque-Bera (JB):                2.287
Skew:                           0.627   Prob(JB):                        0.319
Kurtosis:                       1.979   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [55]:
import pickle
pickle.dump(LR,open('YearsExperience_model.pkl','wb'))

In [57]:
model=pickle.load(open('YearsExperience_model.pkl','rb'))
model

LinearRegression()